# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - good first issue
# Label to use when marking as stale
staleLabel: stale
# Comment to post when marking as stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue
closeComment: >
  This issue has been automatically closed due to inactivity. If you believe
  this is still relevant, please feel free to reopen or create a new issue.
  